import { createHash, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";

/**
 * There are exactly two users. Ever. Their identity is config, not a table you
 * sign up into — the row in `users` is created on first sign-in from these
 * constants.
 *
 * Auth is a password each, not a shared one. The PRD is right that a single
 * shared password kills the whole app: `both sides` depends on knowing *who*
 * wrote which version, and who uploaded which photo. Two passwords keep that
 * and drop the Google dependency.
 */
export type Handle = "manno" | "momo";

export const PEOPLE: Record<Handle, {
  handle: Handle;
  displayName: string;
  accent: string;
  emailKey: string;
  passwordKey: string;
  hashKey: string;
}> = {
  manno: {
    handle: "manno",
    displayName: "Manan",
    accent: "#2E5E4E",
    emailKey: "MANNO_EMAIL",
    passwordKey: "MANNO_PASSWORD",
    hashKey: "MANNO_PASSWORD_HASH",
  },
  momo: {
    handle: "momo",
    displayName: "Nehal",
    accent: "#9B3B66",
    emailKey: "MOMO_EMAIL",
    passwordKey: "MOMO_PASSWORD",
    hashKey: "MOMO_PASSWORD_HASH",
  },
};

export const HANDLES = Object.keys(PEOPLE) as Handle[];
export const OTHER: Record<Handle, Handle> = { manno: "momo", momo: "manno" };

export function isHandle(v: unknown): v is Handle {
  return v === "manno" || v === "momo";
}

/** Email from env, or a local placeholder before setup. */
export function emailFor(handle: Handle): string {
  const set = process.env[PEOPLE[handle].emailKey]?.trim().toLowerCase();
  return set || `${handle}@mannomomo.local`;
}

/** Resolve a login email back to manno or momo. */
export function handleFromEmail(raw: string): Handle | null {
  const email = raw.trim().toLowerCase();
  if (!email) return null;
  for (const handle of HANDLES) {
    if (emailFor(handle) === email) return handle;
  }
  return null;
}

/* ─────────────────────────────────────────────────────────────
   passwords
   ───────────────────────────────────────────────────────────── */

const SCRYPT = { N: 16384, r: 8, p: 1, keylen: 64 };

/**
 * `scrypt:<salt-hex>:<key-hex>` — generated by `npm run set-password`.
 *
 * The separator is a colon, not the conventional `$`, on purpose: Next.js
 * runs .env values through dotenv-expand, which treats `$name` as a variable
 * reference and silently expands it to nothing. A `$`-delimited hash arrives
 * at the server mangled and every login fails with no useful error.
 */
export function hashPassword(password: string, salt = randomBytes(16)): string {
  const key = scryptSync(password.normalize("NFKC"), salt, SCRYPT.keylen, SCRYPT);
  return `scrypt:${salt.toString("hex")}:${key.toString("hex")}`;
}

function verifyAgainstHash(password: string, stored: string): boolean {
  const [scheme, saltHex, keyHex] = stored.split(":");
  if (scheme !== "scrypt" || !saltHex || !keyHex) return false;
  try {
    const expected = Buffer.from(keyHex, "hex");
    const actual = scryptSync(password.normalize("NFKC"), Buffer.from(saltHex, "hex"), expected.length, SCRYPT);
    return timingSafeEqual(expected, actual);
  } catch {
    return false;
  }
}

/** Compare plaintext without leaking length through timing. */
function verifyAgainstPlain(password: string, stored: string): boolean {
  const a = createHash("sha256").update(password.normalize("NFKC")).digest();
  const b = createHash("sha256").update(stored.normalize("NFKC")).digest();
  return timingSafeEqual(a, b);
}

/**
 * A hash wins if one is set. Plaintext in the env is accepted as a fallback
 * because the env file already holds the R2 secret key — it is the trust
 * boundary either way — and being locked out of your own archive by a
 * hashing step you got wrong is a worse outcome than the marginal risk.
 */
export function verifyPassword(handle: Handle, password: string): boolean {
  if (!password) return false;
  const person = PEOPLE[handle];

  const hash = process.env[person.hashKey]?.trim();
  if (hash) return verifyAgainstHash(password, hash);

  const plain = process.env[person.passwordKey]?.trim();
  if (plain) return verifyAgainstPlain(password, plain);

  return false;
}

export function hasPassword(handle: Handle): boolean {
  return Boolean(process.env[PEOPLE[handle].hashKey]?.trim() || process.env[PEOPLE[handle].passwordKey]?.trim());
}

/** Which of the two can actually log in right now. */
export function configuredHandles(): Handle[] {
  return HANDLES.filter(hasPassword);
}

export const authConfigured = () => Boolean(process.env.AUTH_SECRET?.trim()) && configuredHandles().length > 0;

/**
 * True only when it is safe to browse without signing in: a dev machine that
 * has no password set yet, so you can see the shell before doing the setup.
 *
 * This must never be true in production. Without the NODE_ENV check, deploying
 * before running `npm run set-password` would publish the entire archive to
 * anyone holding the URL — the one failure mode this app cannot have.
 */
export function unlockedForSetup(): boolean {
  return process.env.NODE_ENV !== "production" && !authConfigured();
}
